version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=hack101cool'
      - 'POSTGRES_DB=Library'

  app:
    build: .
    container_name: 'java-app'
    ports:
      - "8080:8080"


